[project]
name = "free-win"
version = "0.1.0"
description = "Aplicacion web para gestionar pedidos comunitarios de cartas"
authors = [
    {name = "Pedro"},
]
dependencies = [
    "uvicorn[standard]>=0.34.0",
    "litestar>=2.15.1",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
    "sqlalchemy>=2.0.39",
    "alembic>=1.15.1",
    "aiosqlite>=0.22.1",
    "httpx>=0.28.1",
    "beautifulsoup4>=4.14.3",
    "openpyxl>=3.1.5",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false
