[project]
name = "free-win"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Pedro"},
    {name = "Pedro", email = "87550035+odiseo0@users.noreply.github.com"},
]
dependencies = [
    "fastapi[standard]>=0.138.2",
    "SQLAlchemy>=2.0.51",
    "asyncpg>=0.31.0",
    "httptools>=0.8.0",
    "pytest>=9.1.1",
    "valkey>=6.1.1",
    "alembic>=1.18.5",
    "pytz>=2026.2",
    "orjson>=3.11.9",
]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[tool.basedpyright]
exclude = ["**/node_modules", "**/__pycache__", ".venv"]
typeCheckingMode = "basic"
reportUnnecessaryTypeIgnoreComment = true
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportReturnType = false
reportArgumentType = false
