"""add OrderRequest

Revision ID: b3a7ea35b324
Revises: 20260722_02
Create Date: 2026-07-22 15:06:08.460131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3a7ea35b324'
down_revision: Union[str, Sequence[str], None] = '20260722_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_period_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='submitted', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency = 'USD'", name=op.f('ck_order_requests_valid_currency')),
    sa.CheckConstraint("status IN ('submitted', 'in_review', 'accepted', 'rejected', 'cancelled')", name=op.f('ck_order_requests_valid_status')),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], name=op.f('fk_order_requests_cancelled_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_order_requests_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['order_period_id'], ['order_periods.id'], name=op.f('fk_order_requests_order_period_id_order_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_requests'))
    )
    op.create_index('ix_order_requests_created_by_user_id', 'order_requests', ['created_by_user_id'], unique=False)
    op.create_index('ix_order_requests_order_period_id', 'order_requests', ['order_period_id'], unique=False)
    op.create_index('ix_order_requests_period_status', 'order_requests', ['order_period_id', 'status'], unique=False)
    op.create_index('ix_order_requests_status', 'order_requests', ['status'], unique=False)
    op.create_table('order_request_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_request_id', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("event IN ('created', 'updated', 'status_changed', 'item_added', 'item_updated', 'item_removed', 'item_restored')", name=op.f('ck_order_request_histories_valid_event')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_order_request_histories_actor_user_id_users')),
    sa.ForeignKeyConstraint(['order_request_id'], ['order_requests.id'], name=op.f('fk_order_request_histories_order_request_id_order_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_request_histories'))
    )
    op.create_index('ix_order_request_histories_actor_user_id', 'order_request_histories', ['actor_user_id'], unique=False)
    op.create_index('ix_order_request_histories_request_occurred', 'order_request_histories', ['order_request_id', 'occurred_at'], unique=False)
    op.create_table('order_request_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_request_id', sa.BigInteger(), nullable=False),
    sa.Column('card_listing_id', sa.BigInteger(), nullable=False),
    sa.Column('card_name', sa.String(length=255), nullable=False),
    sa.Column('card_set', sa.String(length=255), nullable=False),
    sa.Column('card_code', sa.String(length=64), nullable=False),
    sa.Column('rarity', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('estimated_unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('agreed_quantity', sa.Integer(), nullable=False),
    sa.Column('card_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipping_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(card_unit_price IS NULL OR card_unit_price >= 0) AND (shipping_unit_price IS NULL OR shipping_unit_price >= 0) AND (tax_unit_price IS NULL OR tax_unit_price >= 0)', name=op.f('ck_order_request_items_non_negative_final_prices')),
    sa.CheckConstraint('agreed_quantity >= 0', name=op.f('ck_order_request_items_non_negative_agreed_quantity')),
    sa.CheckConstraint('estimated_unit_price >= 0', name=op.f('ck_order_request_items_non_negative_estimated_unit_price')),
    sa.CheckConstraint('requested_quantity > 0', name=op.f('ck_order_request_items_positive_requested_quantity')),
    sa.ForeignKeyConstraint(['card_listing_id'], ['card_listings.id'], name=op.f('fk_order_request_items_card_listing_id_card_listings')),
    sa.ForeignKeyConstraint(['order_request_id'], ['order_requests.id'], name=op.f('fk_order_request_items_order_request_id_order_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['removed_by_user_id'], ['users.id'], name=op.f('fk_order_request_items_removed_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_request_items')),
    sa.UniqueConstraint('order_request_id', 'card_listing_id', name='uq_order_request_items_request_listing')
    )
    op.create_index('ix_order_request_items_card_listing_id', 'order_request_items', ['card_listing_id'], unique=False)
    op.create_index('ix_order_request_items_order_request_id', 'order_request_items', ['order_request_id'], unique=False)
    op.create_index('ix_order_request_items_request_removed', 'order_request_items', ['order_request_id', 'removed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_request_items_request_removed', table_name='order_request_items')
    op.drop_index('ix_order_request_items_order_request_id', table_name='order_request_items')
    op.drop_index('ix_order_request_items_card_listing_id', table_name='order_request_items')
    op.drop_table('order_request_items')
    op.drop_index('ix_order_request_histories_request_occurred', table_name='order_request_histories')
    op.drop_index('ix_order_request_histories_actor_user_id', table_name='order_request_histories')
    op.drop_table('order_request_histories')
    op.drop_index('ix_order_requests_status', table_name='order_requests')
    op.drop_index('ix_order_requests_period_status', table_name='order_requests')
    op.drop_index('ix_order_requests_order_period_id', table_name='order_requests')
    op.drop_index('ix_order_requests_created_by_user_id', table_name='order_requests')
    op.drop_table('order_requests')
    # ### end Alembic commands ###
