"""allow NULL on attribute

Revision ID: ceb773a87f58
Revises: ed33c2e1cf00
Create Date: 2026-07-24 15:00:33.317685

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ceb773a87f58"
down_revision: Union[str, Sequence[str], None] = "ed33c2e1cf00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cards", "attribute", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cards", "attribute", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
